### ISSUE TITLE
issues with latest  version 2024.2.2

### ISSUE THREAD

**Issue by antoniomolram** [dbuezas/eq3btsmart#108]
Hi,

First of all, thank you for your amazing job! ;)

today I updated to the latest home assistant 2024.2.2, and seems to be broken. Could you check it? (it seems something related with the update to python 3.12).

Thank in advance,

LOG:
```
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 17 de febrero de 2024, 19:40:57 (1 occurrences)
Last logged: 17 de febrero de 2024, 19:40:57

Setup failed for custom integration 'dbuezas_eq3btsmart': Unable to import component: No module named 'imp'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dbuezas_eq3btsmart/__init__.py", line 5, in <module>
    from .python_eq3bt.eq3bt.eq3btsmart import Thermostat
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/__init__.py", line 2, in <module>
    from .structures import *
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/structures.py", line 4, in <module>
    from construct import (
  File "/usr/local/lib/python3.12/site-packages/construct/__init__.py", line 22, in <module>
    from construct.core import *
  File "/usr/local/lib/python3.12/site-packages/construct/core.py", line 3, in <module>
    import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
ModuleNotFoundError: No module named 'imp'
```

**Comment by EuleMitKeule** [comment]
Duplicate of #106

**Comment by dbuezas** [comment]
Hey @antoniomolram , thanks for your nice words :)

I haven't updated my Home Assistant yet, have you updated the component as @EuleMitKeule suggests?

**Comment by antoniomolram** [comment]
I updated to the v6.3.1 and now works again. Thank you again!
