### ISSUE TITLE
Problem with one device (Characteristic 1056 not found!)

### ISSUE THREAD

**Issue by r-jordan** [dbuezas/eq3btsmart#3]
Hi @dbuezas ,

Thank you very much for the integration!!

I have got 3 of these EQ3 valves and it's working for two of them but it's not connecting to one of the devices and the following errors are showing:

```
Logger: homeassistant.helpers.entity
Source: custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py:97
Integration: dbuezas EQ3 Bluetooth Smart Thermostats
First occurred: 18 d’octubre de 2022, a les 23:14:42 (114 occurrences)
Last logged: 01:30:03

Update for climate.eq3_salon2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 718, in async_device_update
    await task
  File "/config/custom_components/dbuezas_eq3btsmart/climate.py", line 388, in async_update
    await self._async_thermostat_update()
  File "/config/custom_components/dbuezas_eq3btsmart/climate.py", line 381, in _async_thermostat_update
    await self._thermostat.async_update()
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/eq3btsmart.py", line 239, in async_update
    await self._conn.async_make_request(PROP_WRITE_HANDLE, value)
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 111, in async_make_request
    raise ex
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 97, in async_make_request
    await conn.start_notify(
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 546, in start_notify
    raise BleakError(f"Characteristic {char_specifier} not found!")
bleak.exc.BleakError: Characteristic 1056 not found!
```

I know the device is not the cause because it works ok with the bt-mqtt-gateway.

**Comment by dbuezas** [comment]
Can you try unpairing and pairing again? 
Follow this here: https://github.com/rytilahti/python-eq3bt#pairing

Another person with a similar problem reports that solving it in a closed issue in this repo

**Comment by dbuezas** [comment]
It may also be that keeping the devices connected limits making new connections. Bluetooth is very fiddly

**Comment by r-jordan** [comment]
Finally, I managed to solve the problem removing the cache file from /var/lib/bluetooth/.../cache/... , restarting the bluetooth service from systemctl and pairing again de device with the instructions from python-eq3bt.

Thanks a lot!

**Comment by dbuezas** [comment]
Cool! 🎉 
I released v1.0.0 with a better connection approach, it works way better for me now, try upgrading too, it seems to be way faster now
