### ISSUE TITLE
Exception: Device not found

### ISSUE THREAD

**Issue by 0rC0** [dbuezas/eq3btsmart#35]
Hello,

first of all thank you for your work in making this component. I have some issue in adding my devices in HASS. They worked until two days ago as I updated from the version 2022.04 to the latest stable, and they work if I add them to CalorBT app. I tried the whole procedure a couple of time for each device with the same result.

HASS: 2023.1.4 Docker
OS: RaspiOS on Raspberry 3B
Device MAC: 00:1A:22:16:C5:0D - last firmware version, the device is located 0.5-1 meter from the raspi.
dbuezas_eq3btsmart version: 4.0.1 from HACS

.... after deleting the devices from CalorBT, deactivating phone BT (just to be sure), factory reset of device, and pairing as described in the README.md:

`bluetoothctl`:
```
[bluetooth]# trust 00:1A:22:16:C5:0D
[CHG] Device 00:1A:22:16:C5:0D Trusted: yes
Changing 00:1A:22:16:C5:0D trust succeeded
[bluetooth]# pair 00:1A:22:16:C5:0D
Attempting to pair with 00:1A:22:16:C5:0D
[CHG] Device 00:1A:22:16:C5:0D Connected: yes
Request passkey
[agent] Enter passkey (number in 0-999999): [NEW] Primary Service (Handle 0x6db4)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/service0200
	00001801-0000-1000-8000-00805f9b34fb
	Generic Attribute Profile
[agent] Enter passkey (number in 0-999999): [NEW] Characteristic (Handle 0x006c)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/service0200/char0210
	00002a05-0000-1000-8000-00805f9b34fb
	Service Changed
[agent] Enter passkey (number in 0-999999): [NEW] Descriptor (Handle 0xe4fc)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/service0200/char0210/desc0220
	00002902-0000-1000-8000-00805f9b34fb
	Client Characteristic Configuration
[agent] Enter passkey (number in 0-999999): [NEW] Primary Service (Handle 0x9b34)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/service0300
	0000180a-0000-1000-8000-00805f9b34fb
	Device Information
[agent] Enter passkey (number in 0-999999): [NEW] Characteristic (Handle 0x006c)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/service0300/char0310
	00002a29-0000-1000-8000-00805f9b34fb
	Manufacturer Name String
[agent] Enter passkey (number in 0-999999): [NEW] Characteristic (Handle 0x006c)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/service0300/char0320
	00002a24-0000-1000-8000-00805f9b34fb
	Model Number String
[agent] Enter passkey (number in 0-999999): [NEW] Primary Service (Handle 0xa30c)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/service0400
	3e135142-654f-9090-134a-a6ff5bb77046
	Vendor specific
[agent] Enter passkey (number in 0-999999): [NEW] Characteristic (Handle 0x006c)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/service0400/char0410
	3fa4585a-ce4a-3bad-db4b-b8df8179ea09
	Vendor specific
[agent] Enter passkey (number in 0-999999): [NEW] Characteristic (Handle 0x006c)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/service0400/char0420
	d0e8434d-cd29-0996-af41-6c90f4e0eb2a
	Vendor specific
[agent] Enter passkey (number in 0-999999): [NEW] Descriptor (Handle 0xe4fc)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/service0400/char0420/desc0430
	00002902-0000-1000-8000-00805f9b34fb
	Client Characteristic Configuration
[agent] Enter passkey (number in 0-999999): [NEW] Primary Service (Handle 0x7940)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/serviceff00
	9e5d1e47-5c13-43a0-8635-82ad38a1386f
	Vendor specific
[agent] Enter passkey (number in 0-999999): [NEW] Characteristic (Handle 0x006c)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/serviceff00/charff01
	e3dd50bf-f7a7-4e99-838e-570a086c666b
	Vendor specific
[agent] Enter passkey (number in 0-999999): [NEW] Descriptor (Handle 0xe4fc)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/serviceff00/charff01/descff03
	00002902-0000-1000-8000-00805f9b34fb
	Client Characteristic Configuration
[agent] Enter passkey (number in 0-999999): [NEW] Characteristic (Handle 0x006c)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/serviceff00/charff04
	92e86c7a-d961-4091-b74f-2409e72efe36
	Vendor specific
[agent] Enter passkey (number in 0-999999): [NEW] Characteristic (Handle 0x006c)
	/org/bluez/hci0/dev_00_1A_22_16_C5_0D/serviceff00/charff06
	347f7608-2e2d-47eb-913b-75d4edc4de3b
	Vendor specific
[agent] Enter passkey (number in 0-999999): [CHG] Device 00:1A:22:16:C5:0D UUIDs: 00001800-0000-1000-8000-00805f9b34fb
[agent] Enter passkey (number in 0-999999): [CHG] Device 00:1A:22:16:C5:0D UUIDs: 00001801-0000-1000-8000-00805f9b34fb
[agent] Enter passkey (number in 0-999999): [CHG] Device 00:1A:22:16:C5:0D UUIDs: 0000180a-0000-1000-8000-00805f9b34fb
[agent] Enter passkey (number in 0-999999): [CHG] Device 00:1A:22:16:C5:0D UUIDs: 3e135142-654f-9090-134a-a6ff5bb77046
[agent] Enter passkey (number in 0-999999): [CHG] Device 00:1A:22:16:C5:0D UUIDs: 9e5d1e47-5c13-43a0-8635-82ad38a1386f
[agent] Enter passkey (number in 0-999999): [CHG] Device 00:1A:22:16:C5:0D ServicesResolved: yes
[agent] Enter passkey (number in 0-999999): [DEL] Device 6C:AB:46:EF:5D:DC 6C-AB-46-EF-5D-DC
[...]
[agent] Enter passkey (number in 0-999999): XXXXXX
[DEL] Device 72:F3:0B:06:F4:B3 72-F3-0B-06-F4-B3
[DEL] Device 55:0E:51:55:CB:67 55-0E-51-55-CB-67
[CHG] Device 00:1A:22:16:C5:0D Paired: yes
Pairing successful
```
```
Agent registered
[CHG] Controller B8:27:EB:0E:A1:08 Pairable: yes
[bluetooth]# paired-devices
Device 00:1A:22:16:C9:EE CC-RT-BLE
Device 00:1A:22:16:C5:0D CC-RT-BLE
[bluetooth]# info 00:1A:22:16:C5:0D
Device 00:1A:22:16:C5:0D (public)
	Name: CC-RT-BLE
	Alias: CC-RT-BLE
	Paired: yes
	Trusted: yes
	Blocked: no
	Connected: no
	LegacyPairing: no
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
	UUID: Vendor specific           (3e135142-654f-9090-134a-a6ff5bb77046)
	UUID: Vendor specific           (9e5d1e47-5c13-43a0-8635-82ad38a1386f)
```
 
I have waited for about 30 minutes, but no autodiscover. Than I tried to add it manually. The device is not found.

 `homeassistant.log`
```
2023-01-17 01:03:02.984 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/dbuezas_eq3btsmart/sensor.py", line 121, in fetch_serial
    await self._thermostat.async_query_id()
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/eq3btsmart.py", line 160, in async_query_id
    await self._conn.async_make_request(value)
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 174, in async_make_request
    await self._async_make_request_try(value, retries)
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 213, in _async_make_request_try
    raise ex
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 186, in _async_make_request_try
    conn = await self.async_get_connection()
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 94, in async_get_connection
    raise Exception("Device not found")
Exception: Device not found
```

Do someone has some suggestion? 
Thanks in advance. Best,

**Comment by dbuezas** [comment]
That's really weird. I hav

**Comment by dbuezas** [comment]
That's weird,.. i haven't updated HA yet, but the error doesn't look like is due to this integration.
Maybe try reinstalling the Bluetooth integration?

**Comment by dbuezas** [comment]
Ok, I just updated Home Assistant and I have issues. This is exactly the issue I get if the bluetooth integration breaks though, so I assume may be that. Can you confirm your bluetooth integration is added and working properly?

**Comment by 0rC0** [comment]
Hello again. I have tried and you were right. There was some problem with my Bluetooth integrations. I do not know, what exactly was. 
Anyway, after deleting the Bluetooth + this integration and reinstalling them, I can connect my thermostat. :-)

Thank you for the help!
Best,

**Comment by dbuezas** [comment]
Happy to hear!
Turning it off and on again saved the day again 😂
