### ISSUE TITLE
Device not found error

### ISSUE THREAD

**Issue by icemtel** [dbuezas/eq3btsmart#48]
**Problem**
Hass does not connect to the thermostat; logs show "device not found" error.

Pairing via CLI worked. Can connect to the device  (see screenshot)

![image](https://user-images.githubusercontent.com/24736201/216463940-9f5113ac-9cf8-42ed-8303-e5528d7c4ce2.png)

**Logs** (debug mode)
```
2023-02-02 23:25:01.979 ERROR (MainThread) [custom_components.dbuezas_eq3btsmart.climate] [eq3_living_room] Error updating: Device not found
2023-02-02 23:25:24.771 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/dbuezas_eq3btsmart/sensor.py", line 122, in fetch_serial
    await self._thermostat.async_query_id()
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/eq3btsmart.py", line 160, in async_query_id
    await self._conn.async_make_request(value)
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 174, in async_make_request
    await self._async_make_request_try(value, retries)
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 213, in _async_make_request_try
    raise ex
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 186, in _async_make_request_try
    conn = await self.async_get_connection()
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 94, in async_get_connection
    raise Exception("Device not found")
Exception: Device not found
```

**Software versions**
dbuezas_eq3btsmart: v5.0.1
HACS: 1.30.1
Home Assistant 2023.2.0
Supervisor 2023.01.1
Operating System 9.5
Device: raspberry pi 3b+

**Integration options**
![image](https://user-images.githubusercontent.com/24736201/216464532-48f00296-0a6c-4317-bb3b-cb098258bb39.png)

**Comment by dbuezas** [comment]
Is the Bluetooth integration in home assistant running?

**Comment by icemtel** [comment]
@dbuezas 

That's embarrassing, but I noticed that one of my disabled devices was actually the bluetooth adapter.. I disabled months ago as I thought that it was some device from neighbors.
![image](https://user-images.githubusercontent.com/24736201/216543671-e0400b70-ac22-4e5f-b89f-9abbe38b9f73.png)

Now everything works, thank you!

**Comment by dbuezas** [comment]
Don't worry, you're not the first one! :)
