### ISSUE TITLE
AttributeError: 'BluetoothManager' object has no attribute 'async_get_scanner_discovered_devices_and_advertisement_data_by_address'

### ISSUE THREAD

**Issue by toalex77** [dbuezas/eq3btsmart#49]
I get this error after latest updates (Home Assistant 2023.2.2 and eq3btsmart at latest commit b3faa7a):  

```
Feb 05 11:23:14 smooth python3.10[2221]: 2023-02-05 11:23:14.512 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Feb 05 11:23:14 smooth python3.10[2221]: Traceback (most recent call last):
Feb 05 11:23:14 smooth python3.10[2221]:   File "/etc/hass/custom_components/dbuezas_eq3btsmart/sensor.py", line 122, in fetch_serial
Feb 05 11:23:14 smooth python3.10[2221]:     await self._thermostat.async_query_id()
Feb 05 11:23:14 smooth python3.10[2221]:   File "/etc/hass/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/eq3btsmart.py", line 160, in async_query_id
Feb 05 11:23:14 smooth python3.10[2221]:     await self._conn.async_make_request(value)
Feb 05 11:23:14 smooth python3.10[2221]:   File "/etc/hass/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 174, in async_make_request
Feb 05 11:23:14 smooth python3.10[2221]:     await self._async_make_request_try(value, retries)
Feb 05 11:23:14 smooth python3.10[2221]:   File "/etc/hass/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 213, in _async_make_request_try
Feb 05 11:23:14 smooth python3.10[2221]:     raise ex
Feb 05 11:23:14 smooth python3.10[2221]:   File "/etc/hass/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 186, in _async_make_request_try
Feb 05 11:23:14 smooth python3.10[2221]:     conn = await self.async_get_connection()
Feb 05 11:23:14 smooth python3.10[2221]:   File "/etc/hass/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 108, in async_get_connection
Feb 05 11:23:14 smooth python3.10[2221]:     MANAGER.async_get_scanner_discovered_devices_and_advertisement_data_by_address(
Feb 05 11:23:14 smooth python3.10[2221]: AttributeError: 'BluetoothManager' object has no attribute 'async_get_scanner_discovered_devices_and_advertisement_data_by_address'

```
and all my valves are gone.

I can submit a pull request with a fix.
```
diff --git a/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py b/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py
index fbc4ee9..be8b207 100644
--- a/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py
+++ b/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py
@@ -105,10 +105,10 @@ class BleakConnection:
             MANAGER = cast(BluetoothManager, self._hass.data[DATA_MANAGER])
 
             device_advertisement_datas = sorted(
-                MANAGER.async_get_scanner_discovered_devices_and_advertisement_data_by_address(
+                MANAGER.async_scanner_devices_by_address(
                     address=self._mac, connectable=True
                 ),
-                key=lambda device_advertisement_data: device_advertisement_data[2].rssi
+                key=lambda device_advertisement_data: device_advertisement_data.advertisement.rssi
                 or NO_RSSI_VALUE,
                 reverse=True,
             )
@@ -122,14 +122,14 @@ class BleakConnection:
                 list = [
                     x
                     for x in device_advertisement_datas
-                    if (d := x[1].details)
+                    if (d := x.ble_device.details)
                     and d.get("props", {}).get("Adapter") == self._adapter
                 ]
                 if len(list) == 0:
                     raise Exception("Device not found")
                 d_and_a = list[0]
-            self.rssi = d_and_a[2].rssi
-            self._ble_device = d_and_a[1]
+            self.rssi = d_and_a.advertisement.rssi
+            self._ble_device = d_and_a.ble_device
             UnwrappedBleakClient = cast(type[BleakClient], BleakClient.__bases__[0])
             self._conn = UnwrappedBleakClient(
                 self._ble_device,
```

**Comment by dbuezas** [comment]
I left a small request to use the now "user exposed API" in the PR (so that this doesn't break again in the future), let me know if you want do that too. Otherwise I'll merge& release it as is, and look into it when I have time :)

**Comment by toalex77** [comment]
Ok, I'll try it, but I don't know of long it will take me to implement it. I don't develop mainly in Python, but I can try.  
Thanks for the links in the PR.

**Comment by dbuezas** [comment]
This looks perfect to me, you did well!

Have you tested it? I haven't updated HA yet so I can't test it yet.
Let me know and I'll merge and release.

**Comment by toalex77** [comment]
Yes, of course ;)
All bluetooth valves works, and Home Assistant logs are perfectly clean (at least as far as it concern eq3btsmart component).

**Comment by dbuezas** [comment]
Allright, let's go!

**Comment by dbuezas** [comment]
It's out in v5.0.2 🎉
